Try to fix compilation with MSVC 2017
MSVC seems to reject the Unicode character literals because they are
multibyte (error C2015: too many characters in constant) but seems to
work well with the Unicode string literals.

See issue  #1761 and discussion in PR #1810